# These are supported funding model platforms
# Replace with up to 4 GitHub Sponsors- enabled
 
 user: [ FW4248 ]
  proceed: e.g., [user1, user2]
  patreon: [ Ruby , Maven , js node16 ]

# Replace rebase repository with a single Patch 

  user:
   open: 
   collection:
   version: 
 
# Rebase with angular and ci project use
   run:
      Js: 
    secure:



